seed: 42
img_size: 224
batch_size: 32
num_workers: 4
max_epochs: 10
lr: 0.0005
weight_decay: 0.0001
patience: 3
model_name: resnet18
split:
  train: 0.7
  val: 0.15
  test: 0.15
raw_dir: data/raw
out_dir: artifacts